server:
  port: 80
spring:
  thymeleaf:
    cache: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.230.130.100:3306/yycg_project?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  mvc:
    favicon:
      enabled: false
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
     #整合mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.yuan.yiyao: trace

#mybatis plus配置
mybatis-plus:
   #由于本例中采用注解方式编写sql，故而此处可不配置
   #mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.yuan.yiyao.sys.vo
  #枚举扫描配置（本示例未使用到）
  #typeEnumsPackage: com.szss.admin.model.domain
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"UUID";
#    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器(由于本例中采用注解方式编写sql，故而不需要刷新mapper.xml文件)
    #refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    #序列接口实现类配置,在新的mybatis-plus-boot-starter中不推荐此方式进行配置,推荐自定义bean注入
    key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false